Updated for Bannerlord 1.7.2
Hirtol/PartyScreenEnhancements pull request #10
Opened 2022-03-29 13:09 UTC by OrderWOPower

I updated Party Screen Enhancements for Bannerlord 1.7.2. Enjoy!

2022-03-29 13:36 UTC, Hirtol requested changes
Thank you for taking the time to go through this!

The main question for me revolves around the `rosterToSort.Clear();` call. It used to corrupt people's saves so I'm a bit hesitant about it.

It seems Taleworlds added new Dlls which I forgot to import, which broke the ScreenLayer hack. Ended up giving up on updating it a while back due to this breaking. Something to keep in mind for myself in the future.

2022-03-29 13:36 UTC, Hirtol commented on PartyScreenEnhancements/ModuleData/SubModule.xml
> +		<DependedModule Id="Native" DependentVersion="e1.6.5"/>
These version numbers should reference 1.7.2, right?

2022-03-29 13:36 UTC, Hirtol commented on PartyScreenEnhancements/SubModule.cs
> +            UIResourceManager.UIResourceDepot.StartWatchingChangesInDepot();
This should probably be disabled for the Nexus build

2022-03-29 13:36 UTC, Hirtol commented on PartyScreenEnhancements/ViewModel/Settings/Tabs/Sorting/SettingSortVM.cs
> +            SettingHint = new HintViewModel(new TextObject(SortingComparer.GetHintText())); ;
Double semicolons

2022-03-29 13:36 UTC, Hirtol commented on PartyScreenEnhancements/ViewModel/SortAllTroopsVM.cs
> +            rosterToSort.Clear();
Is the above comment no longer relevant? Might be useful to leave a comment why clearing the roster is now safe

2022-03-29 13:36 UTC, Hirtol commented on PartyScreenEnhancements/ViewModel/SortAllTroopsVM.cs
> +            var leaderOfParty = party?.LeaderHero.CharacterObject;
I'd prefer to keep the comments explaining the details of why we're doing the following

2022-03-29 13:36 UTC, Hirtol commented on PartyScreenEnhancements/ViewModel/SortAllTroopsVM.cs
> -            // Re-add the correctly sorted troops to the roster. We need to do it in this janky way due to the fact that we can't easily sort
Probably keep this comment as well

2022-03-30 02:45 UTC, OrderWOPower commented
Hmm, I might have forked a wrong branch... Will try again later.

2022-03-30 18:44 UTC, Hirtol reviewed
Thanks again, I'll merge this and upload it to the Nexus.

2022-03-30 18:45 UTC, Hirtol approved these changes

2022-03-30 18:45 UTC, merged